import { afterAll,describe,expect,it } from 'vitest';
import { createDatabase } from '../src/infrastructure/db/client.js';
import { PostgresBriefRepository } from '../src/infrastructure/db/repository.js';
const url=process.env.TEST_DATABASE_URL;const suite=describe.skipIf(!url);
suite('PostgreSQL repository integration',()=>{
  const connection=createDatabase(url!);const repo=new PostgresBriefRepository(connection.db);const chatA=String(700000000000000+Math.floor(Math.random()*1000000));const chatB=String(Number(chatA)+1);const client={telegramId:chatA,name:'Integration',locale:'en' as const};
  afterAll(async()=>{await repo.deleteChatData(chatA);await repo.deleteChatData(chatB);await connection.pool.end();});
  it('serializes concurrent ingestion into the same selected brief',async()=>{const [a,b]=await Promise.all([repo.ingestMessage({updateId:Number(chatA.slice(-9))+1,telegramMessageId:'1',chatId:chatA,client,source:'text',rawText:'A'}),repo.ingestMessage({updateId:Number(chatA.slice(-9))+2,telegramMessageId:'2',chatId:chatA,client,source:'text',rawText:'B'})]);expect(a.brief.id).toBe(b.brief.id);expect((await repo.history(a.brief.id,10))).toHaveLength(2);});
  it('deduplicates update_id transactionally',async()=>{const updateId=Number(chatA.slice(-9))+3;const first=await repo.ingestMessage({updateId,telegramMessageId:'3',chatId:chatA,client,source:'text',rawText:'One'});const second=await repo.ingestMessage({updateId,telegramMessageId:'3',chatId:chatA,client,source:'text',rawText:'Duplicate'});expect(second.duplicate).toBe(true);expect(second.message.id).toBe(first.message.id);});
  it('stores voice identity before transcription',async()=>{const row=await repo.ingestMessage({updateId:Number(chatA.slice(-9))+4,telegramMessageId:'4',chatId:chatA,client,source:'voice',telegramFileId:'telegram-file'});expect(row.message.stage).toBe('received');expect(row.message.telegramFileId).toBe('telegram-file');});
  it('prevents cross-chat brief selection',async()=>{const foreign=await repo.createBrief(chatB,{telegramId:chatB,name:'Other'},'Other');await expect(repo.selectBrief(chatA,foreign.id)).rejects.toThrow();});
  it('applies only source-grounded facts and writes normalized history',async()=>{const ingested=await repo.ingestMessage({updateId:Number(chatA.slice(-9))+5,telegramMessageId:'5',chatId:chatA,client,source:'text',rawText:'Budget is 5000 EUR'});const result={facts:[{fieldId:'constraints.budget',value:'5000 EUR',operation:'set' as const,status:'confirmed' as const,confidence:1,sourceQuote:'5000 EUR',reason:'explicit',sourceMessageIds:[ingested.message.id]}],conflicts:[],nextQuestions:[],detectedLanguage:'en' as const};const updated=await repo.applyInterview(ingested.brief.id,ingested.brief.version,ingested.message.id,result,'model-session');expect(updated.fields['constraints.budget']?.value).toBe('5000 EUR');const rows=await connection.pool.query('select count(*)::int n from brief_field_history where brief_id=$1',[updated.id]);expect(rows.rows[0].n).toBe(1);});
});
