import { Bot,InputFile,InlineKeyboard } from 'grammy';
import { mkdir,unlink,writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { AppConfig } from '../config/env.js';
import type { BriefRepository,ClientIdentity,PipelineStage,TranscriptionClient } from '../application/ports.js';
import { InterviewService } from '../application/interview-service.js';
import { briefNavigation,finishKeyboard,languageKeyboard,mainKeyboard,moreKeyboard,retryKeyboard } from './keyboards.js';
import { withRetry } from '../infrastructure/retry.js';
import { autoRetry } from '@grammyjs/auto-retry';
import { escapeHtml,renderSectionHtml } from '../domain/markdown.js';
import { t,type Locale } from '../domain/localization.js';

export function createBot(config:AppConfig,service:InterviewService,repository:BriefRepository,stt:TranscriptionClient):Bot{
  const bot=new Bot(config.TELEGRAM_BOT_TOKEN);bot.api.config.use(autoRetry({maxRetryAttempts:3,maxDelaySeconds:8}));
  const identity=(ctx:any,locale?:Locale):ClientIdentity=>({telegramId:String(ctx.from.id),...(ctx.from.username?{username:ctx.from.username}:{}),name:[ctx.from.first_name,ctx.from.last_name].filter(Boolean).join(' '),...(locale?{locale}:{})});
  bot.command('start',async ctx=>{const suggested:Locale=ctx.from?.language_code?.startsWith('ru')?'ru':'en';await service.ensureActive(String(ctx.chat.id),identity(ctx,suggested));await service.setLocale(String(ctx.chat.id),suggested);await ctx.reply(suggested==='ru'?'Выберите язык интерфейса. Бриф уже готов принимать текст и голос.':'Choose the interface language. Your brief is ready for text or voice.',{reply_markup:languageKeyboard});});
  bot.command('help',async ctx=>{const l=await locale(ctx);await ctx.reply(l==='ru'?'Отправьте описание проекта текстом или голосом. /brief — обзор, /briefs — список, /new — новый бриф, /language — язык.':'Send a project description as text or voice. /brief — overview, /briefs — list, /new — new brief, /language — language.',{reply_markup:mainKeyboard(l)});});
  bot.command('brief',ctx=>showBrief(ctx));bot.command('briefs',ctx=>showBriefs(ctx));bot.command('progress',async ctx=>{const l=await locale(ctx);await ctx.reply(escapeHtml(await service.progress(String(ctx.chat.id))),{parse_mode:'HTML',reply_markup:mainKeyboard(l)});});
  bot.command('new',async ctx=>{const l=await locale(ctx);const b=await service.createBrief(String(ctx.chat.id),identity(ctx,l));await ctx.reply(`${l==='ru'?'Создан':'Created'}: <b>${escapeHtml(b.title)}</b>`,{parse_mode:'HTML',reply_markup:mainKeyboard(l)});});
  bot.command('language',ctx=>ctx.reply('Русский / English',{reply_markup:languageKeyboard}));bot.command('finish',ctx=>showFinish(ctx));bot.command('delete',async ctx=>{const l=await locale(ctx);await ctx.reply(l==='ru'?'Удалить все ваши брифы и сообщения? Это действие необратимо.':'Delete all your briefs and messages? This cannot be undone.',{reply_markup:new InlineKeyboard().text(l==='ru'?'Продолжить':'Continue','delete_step_2').text(l==='ru'?'Отмена':'Cancel','cancel')});});
  bot.command('template_copy',async ctx=>{const l=await locale(ctx);const name=String(ctx.match||'').trim()||(l==='ru'?'Мой шаблон':'My template');try{const b=await service.copyActiveTemplate(String(ctx.chat.id),name);await ctx.reply(`${l==='ru'?'Шаблон скопирован':'Template copied'}: <b>${escapeHtml(b.template.name[l])}</b>`,{parse_mode:'HTML'});}catch{await ctx.reply(t(l,'noBrief'));}});
  bot.command('template_field',async ctx=>{const l=await locale(ctx);const [fieldId,mode,order]=String(ctx.match||'').trim().split(/\s+/);if(!fieldId||!['required','optional','off'].includes(mode??'')){await ctx.reply(l==='ru'?'Формат: /template_field field.id required|optional|off [порядок]':'Format: /template_field field.id required|optional|off [order]');return;}try{await service.configureActiveField(String(ctx.chat.id),fieldId,mode as any,order?Number(order):undefined);await ctx.reply(l==='ru'?'Шаблон обновлён; сохранённые ответы не изменены.':'Template updated; saved answers were preserved.');}catch{await ctx.reply(l==='ru'?'Поле не найдено.':'Field not found.');}});
  bot.callbackQuery(/^lang:(ru|en)$/,async ctx=>{const l=ctx.match![1] as Locale;await service.setLocale(String(ctx.chat!.id),l);await ctx.answerCallbackQuery();await ctx.reply(l==='ru'?'Язык изменён. Отправьте описание проекта текстом или голосом.':'Language changed. Send a project description as text or voice.',{reply_markup:mainKeyboard(l)});});
  bot.callbackQuery('show_brief',async ctx=>{await ctx.answerCallbackQuery();await showBrief(ctx);});bot.callbackQuery('show_progress',async ctx=>{await ctx.answerCallbackQuery();const l=await locale(ctx);await ctx.reply(escapeHtml(await service.progress(String(ctx.chat!.id))),{parse_mode:'HTML',reply_markup:mainKeyboard(l)});});
  bot.callbackQuery('my_briefs',async ctx=>{await ctx.answerCallbackQuery();await showBriefs(ctx);});bot.callbackQuery('more',async ctx=>{await ctx.answerCallbackQuery();const l=await locale(ctx);await ctx.reply(l==='ru'?'Дополнительные действия':'More actions',{reply_markup:moreKeyboard(l)});});bot.callbackQuery('language',async ctx=>{await ctx.answerCallbackQuery();await ctx.reply('Русский / English',{reply_markup:languageKeyboard});});
  bot.callbackQuery('new_brief',async ctx=>{await ctx.answerCallbackQuery();const l=await locale(ctx);const b=await service.createBrief(String(ctx.chat!.id),identity(ctx,l));await ctx.reply(`${l==='ru'?'Создан':'Created'}: <b>${escapeHtml(b.title)}</b>`,{parse_mode:'HTML',reply_markup:mainKeyboard(l)});});
  bot.callbackQuery(/^brief:([0-9a-f-]+)$/,async ctx=>{try{const b=await service.selectBrief(String(ctx.chat!.id),ctx.match![1]!);await ctx.answerCallbackQuery();const l=await locale(ctx);await ctx.reply(`${l==='ru'?'Активный бриф':'Active brief'}: <b>${escapeHtml(b.title)}</b>`,{parse_mode:'HTML',reply_markup:mainKeyboard(l)});}catch{await ctx.answerCallbackQuery({text:'Unavailable'});}});
  bot.callbackQuery(/^(section|gaps):(\d+)$/,async ctx=>{await ctx.answerCallbackQuery();const preview=await service.preview(String(ctx.chat!.id));if(!preview)return;const l=await locale(ctx);const page=renderSectionHtml(preview.brief,l,Number(ctx.match![2]),ctx.match![1]==='gaps');await ctx.reply(page.html,{parse_mode:'HTML',reply_markup:briefNavigation(l,page.index,page.total)});});bot.callbackQuery('noop',ctx=>ctx.answerCallbackQuery());
  bot.callbackQuery('finish',async ctx=>{await ctx.answerCallbackQuery();await showFinish(ctx);});bot.callbackQuery('confirm_finish',async ctx=>{await ctx.answerCallbackQuery();const finalized=await service.finalize(String(ctx.chat!.id));if(!finalized)return;const l=await locale(ctx);const safeName=finalized.brief.title.replace(/[^\p{L}\p{N}._-]+/gu,'-').slice(0,60)||'brief';await ctx.replyWithDocument(new InputFile(Buffer.from(finalized.markdown,'utf8'),`${safeName}.md`),{caption:l==='ru'?'Бриф подтверждён и сохранён.':'Brief confirmed and saved.'});});
  bot.callbackQuery('delete_step_1',async ctx=>{await ctx.answerCallbackQuery();const l=await locale(ctx);await ctx.reply(l==='ru'?'Удалить все данные?':'Delete all data?',{reply_markup:new InlineKeyboard().text(l==='ru'?'Продолжить':'Continue','delete_step_2').text(l==='ru'?'Отмена':'Cancel','cancel')});});bot.callbackQuery('delete_step_2',async ctx=>{await ctx.answerCallbackQuery();const l=await locale(ctx);await ctx.reply(l==='ru'?'Последнее подтверждение':'Final confirmation',{reply_markup:new InlineKeyboard().text(l==='ru'?'Удалить':'Delete','confirm_delete').text(l==='ru'?'Отмена':'Cancel','cancel')});});bot.callbackQuery('confirm_delete',async ctx=>{await ctx.answerCallbackQuery();const chatId=String(ctx.chat!.id);const files=await repository.audioFilesForChat(chatId);await repository.deleteChatData(chatId);await Promise.all(files.map(path=>unlink(path).catch(()=>{})));await ctx.reply('Data deleted / Данные удалены');});bot.callbackQuery('cancel',ctx=>ctx.answerCallbackQuery());
  bot.callbackQuery(/^retry:([0-9a-f-]+)$/,async ctx=>{await ctx.answerCallbackQuery();const l=await locale(ctx);const id=ctx.match![1]!;const stored=await repository.getMessage(id);if(!stored||stored.chatId!==String(ctx.chat!.id)){await ctx.reply(l==='ru'?'Действие недоступно.':'Action unavailable.');return;}if(stored.source==='voice'&&!stored.storedFilePath&&stored.telegramFileId){try{const path=await downloadVoice(ctx,stored.telegramFileId,id);await service.attachAudio(id,path);}catch{await ctx.reply(escapeHtml(t(l,'asrError') as string),{parse_mode:'HTML',reply_markup:retryKeyboard(l,id)});return;}}const status=await ctx.reply(`⏳ ${t(l,'received')}`);const result=await service.retry(id,stt,statusUpdater(ctx,status.message_id,l));await ctx.api.editMessageText(ctx.chat!.id,status.message_id,escapeHtml(result.reply),{parse_mode:'HTML',reply_markup:result.recoverable&&result.messageId?retryKeyboard(l,result.messageId):mainKeyboard(l)});});
  bot.on('message:voice',async ctx=>{const l=await locale(ctx);const voice=ctx.message.voice;if(voice.duration>config.MAX_VOICE_DURATION_SECONDS||(voice.file_size??0)>config.MAX_VOICE_BYTES){await ctx.reply(l==='ru'?'Голосовое превышает лимит.':'Voice message exceeds the limit.');return;}const ingested=await service.ingestVoice({updateId:ctx.update.update_id,chatId:String(ctx.chat.id),client:identity(ctx,l),telegramMessageId:String(ctx.message.message_id),fileId:voice.file_id});if(ingested.duplicate)return;const status=await ctx.reply(`⏳ ${t(l,'received')} · <b>${escapeHtml(ingested.brief.title)}</b>`,{parse_mode:'HTML'});try{await statusUpdater(ctx,status.message_id,l)('audio_saved');await mkdir(resolve(config.AUDIO_STORAGE_DIR),{recursive:true,mode:0o700});const path=resolve(config.AUDIO_STORAGE_DIR,`${ingested.message.id}.ogg`);const file=await withRetry(()=>ctx.api.getFile(voice.file_id));if(!file.file_path)throw new Error('TELEGRAM_FILE_PATH_MISSING');const response=await withRetry(()=>fetch(`https://api.telegram.org/file/bot${config.TELEGRAM_BOT_TOKEN}/${file.file_path}`,{signal:AbortSignal.timeout(30000)}));if(!response.ok)throw new Error(`TELEGRAM_DOWNLOAD_${response.status}`);const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.byteLength>config.MAX_VOICE_BYTES)throw new Error('VOICE_TOO_LARGE');await writeFile(path,bytes,{mode:0o600});await service.attachAudio(ingested.message.id,path);const result=await service.processVoice({...ingested.message,storedFilePath:path,stage:'audio_saved'},ingested.brief,stt,statusUpdater(ctx,status.message_id,l));await ctx.api.editMessageText(ctx.chat.id,status.message_id,escapeHtml(result.reply),{parse_mode:'HTML',reply_markup:result.recoverable&&result.messageId?retryKeyboard(l,result.messageId):mainKeyboard(l)});}catch{await repository.updateMessage(ingested.message.id,{stage:'failed',failedStage:'audio_saved',errorCode:'TELEGRAM_DOWNLOAD_FAILED'});await ctx.api.editMessageText(ctx.chat.id,status.message_id,escapeHtml(t(l,'asrError') as string),{parse_mode:'HTML',reply_markup:retryKeyboard(l,ingested.message.id)});}});
  bot.on('message:text',async ctx=>{if(ctx.message.text.startsWith('/'))return;const l=await locale(ctx);if(ctx.message.text.length>config.MAX_TEXT_LENGTH){await ctx.reply(l==='ru'?'Разделите сообщение на несколько частей.':'Split the message into smaller parts.');return;}await ctx.replyWithChatAction('typing');const status=await ctx.reply(`⏳ ${t(l,'received')}`);const result=await service.process(ctx.update.update_id,String(ctx.chat.id),identity(ctx,l),String(ctx.message.message_id),ctx.message.text,undefined,statusUpdater(ctx,status.message_id,l));if(result.duplicate){await ctx.api.deleteMessage(ctx.chat.id,status.message_id).catch(()=>{});return;}await ctx.api.editMessageText(ctx.chat.id,status.message_id,escapeHtml(result.reply),{parse_mode:'HTML',reply_markup:result.recoverable&&result.messageId?retryKeyboard(l,result.messageId):mainKeyboard(l)});});
  bot.catch(({error})=>console.error('Telegram update failed',error instanceof Error?error.message:'unknown error'));return bot;
  async function locale(ctx:any):Promise<Locale>{return service.getLocale(String(ctx.chat!.id));}
  async function showBrief(ctx:any){const preview=await service.preview(String(ctx.chat.id));const l=await locale(ctx);if(!preview){await ctx.reply(t(l,'noBrief'));return;}const total=preview.brief.template.sections.filter(s=>s.enabled).length;await ctx.reply(preview.html,{parse_mode:'HTML',reply_markup:briefNavigation(l,0,total)});}
  async function showBriefs(ctx:any){const l=await locale(ctx);const list=await service.listBriefs(String(ctx.chat.id));if(!list.length){await ctx.reply(t(l,'noBrief'));return;}const k=new InlineKeyboard();for(const brief of list.slice(0,12))k.text(`${brief.status==='active'?'●':'○'} ${brief.title.slice(0,28)}`,`brief:${brief.id}`).row();await ctx.reply(l==='ru'?'Выберите бриф:':'Choose a brief:',{reply_markup:k});}
  async function showFinish(ctx:any){const preview=await service.preview(String(ctx.chat.id));const l=await locale(ctx);if(!preview){await ctx.reply(t(l,'noBrief'));return;}await ctx.reply(`${preview.html}\n\n${l==='ru'?'Проверьте данные перед экспортом.':'Review the data before export.'}`,{parse_mode:'HTML',reply_markup:finishKeyboard(l)});}
  async function downloadVoice(ctx:any,fileId:string,messageId:string):Promise<string>{await mkdir(resolve(config.AUDIO_STORAGE_DIR),{recursive:true,mode:0o700});const path=resolve(config.AUDIO_STORAGE_DIR,`${messageId}.ogg`);const file:any=await withRetry(()=>ctx.api.getFile(fileId));if(!file.file_path)throw new Error('TELEGRAM_FILE_PATH_MISSING');const response=await withRetry(()=>fetch(`https://api.telegram.org/file/bot${config.TELEGRAM_BOT_TOKEN}/${file.file_path}`,{signal:AbortSignal.timeout(30000)}));if(!response.ok)throw new Error(`TELEGRAM_DOWNLOAD_${response.status}`);const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.byteLength>config.MAX_VOICE_BYTES)throw new Error('VOICE_TOO_LARGE');await writeFile(path,bytes,{mode:0o600});return path;}
}
function statusUpdater(ctx:any,messageId:number,locale:Locale){let last=0;return async(stage:PipelineStage)=>{const now=Date.now();if(now-last<800&&stage!=='completed')return;last=now;const key:Record<PipelineStage,string>={received:'received',audio_saved:'prepareAudio',transcribing:'transcribing',transcribed:'transcribing',extracting:'extracting',extracted:'extracting',saving:'saving',completed:'done',failed:'temporaryError'};const label=t(locale,key[stage] as any) as string;await ctx.api.editMessageText(ctx.chat.id,messageId,`⏳ ${escapeHtml(label)}`,{parse_mode:'HTML'}).catch(()=>{});};}
