import { randomUUID } from 'node:crypto';
import type { Brief,BriefFields,TemplateDefinition } from '../../domain/brief.js';
import { builtInDesignTemplate,calculateProgress } from '../../domain/brief.js';
import type { BriefRepository,ClientIdentity,DialogueMessage,ModelCallMetadata,StoredMessage } from '../../application/ports.js';
import type { InterviewResult } from '../../domain/interview.js';
import type { Locale } from '../../domain/localization.js';
export class InMemoryBriefRepository implements BriefRepository{
  readonly briefs=new Map<string,Brief>(); readonly messages=new Map<string,StoredMessage>(); readonly processed=new Map<number,string>();
  readonly snapshots:Array<{id:string;briefId:string;markdown:string;fields:BriefFields}>=[]; readonly modelCalls:ModelCallMetadata[]=[];
  readonly active=new Map<string,string>(); readonly locales=new Map<string,Locale>();
  readonly messageRows:Array<{id:string;chatId:string;briefId:string;role:'user'|'assistant';text:string}>=[];
  async ensureActive(chatId:string,client:ClientIdentity){const b=await this.getActive(chatId);return b??this.createBrief(chatId,client);}
  async createBrief(chatId:string,client:ClientIdentity,title?:string,template:TemplateDefinition=builtInDesignTemplate){const now=new Date().toISOString();const brief:Brief={id:randomUUID(),chatId,title:title??template.name[client.locale??'ru'],shortCode:randomUUID().slice(0,6).toUpperCase(),status:'active',template,fields:{},progress:0,version:0,createdAt:now,updatedAt:now};this.briefs.set(brief.id,brief);this.active.set(chatId,brief.id);this.locales.set(chatId,client.locale??this.locales.get(chatId)??'ru');return brief;}
  async getActive(chatId:string){const id=this.active.get(chatId);const b=id?this.briefs.get(id):undefined;return b?.status==='active'?b:undefined;}
  async listBriefs(chatId:string){return[...this.briefs.values()].filter(b=>b.chatId===chatId);}
  async selectBrief(chatId:string,briefId:string){const b=this.briefs.get(briefId);if(!b||b.chatId!==chatId||b.status!=='active')throw new Error('Brief unavailable');this.active.set(chatId,briefId);return b;}
  async renameBrief(chatId:string,briefId:string,title:string){const b=this.briefs.get(briefId);if(b?.chatId===chatId)this.briefs.set(briefId,{...b,title});}
  async archiveBrief(chatId:string,briefId:string){const b=this.briefs.get(briefId);if(b?.chatId===chatId)this.briefs.set(briefId,{...b,status:'archived'});if(this.active.get(chatId)===briefId)this.active.delete(chatId);}
  async ingestMessage(input:Parameters<BriefRepository['ingestMessage']>[0]){const duplicateId=this.processed.get(input.updateId);if(duplicateId){const message=this.messages.get(duplicateId)!;return{message,brief:this.briefs.get(message.briefId)!,duplicate:true};}const brief=await this.ensureActive(input.chatId,input.client);const message:StoredMessage={id:randomUUID(),updateId:input.updateId,telegramMessageId:input.telegramMessageId,chatId:input.chatId,briefId:brief.id,sessionId:`session:${brief.id}`,source:input.source,stage:'received',attempts:0,...(input.rawText?{rawText:input.rawText}:{}),...(input.telegramFileId?{telegramFileId:input.telegramFileId}:{})};this.messages.set(message.id,message);this.processed.set(input.updateId,message.id);this.messageRows.push({id:message.id,chatId:input.chatId,briefId:brief.id,role:'user',text:input.rawText??''});return{message,brief,duplicate:false};}
  async updateMessage(id:string,patch:Parameters<BriefRepository['updateMessage']>[1]){const m=this.messages.get(id);if(!m)return;const updated:StoredMessage={...m,...(patch.stage?{stage:patch.stage}:{}),...(patch.storedFilePath?{storedFilePath:patch.storedFilePath}:{}),...(patch.transcript!==undefined?{transcript:patch.transcript}:{}),...(patch.language?{language:patch.language}:{}),...(patch.failedStage?{failedStage:patch.failedStage}:{}),...(patch.errorCode?{errorCode:patch.errorCode}:{}),attempts:m.attempts+(patch.incrementAttempts?1:0)};this.messages.set(id,updated);const row=this.messageRows.find(x=>x.id===id);if(row&&patch.transcript!==undefined)row.text=patch.transcript;if(patch.modelCalls)this.modelCalls.push(...patch.modelCalls);}
  async getMessage(id:string){return this.messages.get(id);}
  async recoverableMessages(limit:number){return[...this.messages.values()].filter(m=>m.stage==='failed'&&m.attempts<3&&(!!m.rawText||!!m.transcript)).slice(0,limit);}
  async history(briefId:string,limit:number):Promise<DialogueMessage[]>{return this.messageRows.filter(m=>m.briefId===briefId).slice(-limit).map(m=>({id:m.id,role:m.role,text:m.text}));}
  async applyInterview(briefId:string,expectedVersion:number,messageId:string,result:InterviewResult,sessionId:string,modelCalls:ModelCallMetadata[]=[]){const current=this.briefs.get(briefId);if(!current||current.version!==expectedVersion)throw new Error('Optimistic lock conflict');const source=(this.messages.get(messageId)?.transcript??this.messages.get(messageId)?.rawText??'').toLowerCase();const fields=structuredClone(current.fields);for(const p of result.facts){const def=current.template.fields.find(f=>f.id===p.fieldId&&f.enabled);if(!def||p.status==='inferred'&&!def.modelMayInfer||p.status==='confirmed'&&!source.includes(p.sourceQuote.toLowerCase()))continue;const old=fields[p.fieldId];if(old?.status==='confirmed'&&JSON.stringify(old.value)!==JSON.stringify(p.value)&&p.operation!=='correct'){fields[p.fieldId]={...old,status:'conflicting',updatedAt:new Date().toISOString()};continue;}fields[p.fieldId]={value:p.value,status:p.status,confidence:p.confidence,sourceMessageIds:[messageId],sourceQuote:p.sourceQuote,reason:p.reason,updatedAt:new Date().toISOString()};}const updated:Brief={...current,fields,progress:calculateProgress(fields,current.template),version:current.version+1,opencodeSessionId:sessionId,updatedAt:new Date().toISOString()};this.briefs.set(briefId,updated);await this.updateMessage(messageId,{stage:'completed',modelCalls});return updated;}
  async preview(){} async finalize(briefId:string,markdown:string){const b=this.briefs.get(briefId);if(!b||b.status!=='active')throw new Error('not active');const id=randomUUID();this.snapshots.push({id,briefId,markdown,fields:structuredClone(b.fields)});const updated:Brief={...b,status:'finalized'};this.briefs.set(briefId,updated);this.active.delete(b.chatId);return{snapshotId:id,brief:updated};}
  async cancelActive(chatId:string){const b=await this.getActive(chatId);if(b)await this.archiveBrief(chatId,b.id);} async deleteChatData(chatId:string){for(const[id,b]of this.briefs)if(b.chatId===chatId)this.briefs.delete(id);this.active.delete(chatId);}
  async audioFilesForChat(chatId:string){return[...this.messages.values()].filter(m=>m.chatId===chatId&&m.storedFilePath).map(m=>m.storedFilePath!);}
  async getLocale(chatId:string){return this.locales.get(chatId)??'ru';} async setLocale(chatId:string,locale:Locale){this.locales.set(chatId,locale);}
  async saveTemplateForActive(chatId:string,template:TemplateDefinition){const b=await this.getActive(chatId);if(!b)throw new Error('No active brief');const updated={...b,template,progress:calculateProgress(b.fields,template),version:b.version+1,updatedAt:new Date().toISOString()};this.briefs.set(b.id,updated);return updated;}
}
