import { bigint, boolean, check, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import type { BriefFields, TemplateDefinition } from '../../domain/brief.js';
import type { InterviewResult } from '../../domain/interview.js';
import type { ModelCallMetadata } from '../../application/ports.js';

export const briefStatus=pgEnum('brief_status',['active','finalized','archived','cancelled']);
export const fieldStatus=pgEnum('field_status',['confirmed','inferred','missing','conflicting','skipped','not_applicable']);
export const messageRole=pgEnum('message_role',['user','assistant']);
export const messageSource=pgEnum('message_source',['text','voice']);
export const pipelineStage=pgEnum('pipeline_stage',['received','audio_saved','transcribing','transcribed','extracting','extracted','saving','completed','failed']);
export const locale=pgEnum('locale',['ru','en']);

export const telegramUsers=pgTable('telegram_users',{id:uuid('id').defaultRandom().primaryKey(),telegramId:bigint('telegram_id',{mode:'bigint'}).notNull().unique(),username:text('username'),name:text('name').notNull(),locale:locale('locale').default('ru').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull()});
export const chats=pgTable('chats',{id:uuid('id').defaultRandom().primaryKey(),telegramChatId:bigint('telegram_chat_id',{mode:'bigint'}).notNull().unique(),userId:uuid('user_id').notNull().references(()=>telegramUsers.id,{onDelete:'cascade'}),activeBriefId:uuid('active_brief_id'),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()});
export const briefTemplates=pgTable('brief_templates',{id:uuid('id').defaultRandom().primaryKey(),ownerUserId:uuid('owner_user_id').references(()=>telegramUsers.id,{onDelete:'cascade'}),key:text('key').notNull(),version:integer('version').notNull(),definition:jsonb('definition').$type<TemplateDefinition>().notNull(),builtIn:boolean('built_in').default(false).notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex('template_owner_key_version_unique').on(t.ownerUserId,t.key,t.version)]);
export const briefs=pgTable('briefs',{id:uuid('id').defaultRandom().primaryKey(),chatId:uuid('chat_id').notNull().references(()=>chats.id,{onDelete:'cascade'}),title:text('title').notNull(),shortCode:text('short_code').notNull(),templateKey:text('template_key').notNull(),templateVersion:integer('template_version').notNull(),templateSnapshot:jsonb('template_snapshot').$type<TemplateDefinition>().notNull(),status:briefStatus('status').default('active').notNull(),fields:jsonb('fields').$type<BriefFields>().default({}).notNull(),progress:integer('progress').default(0).notNull(),version:integer('version').default(0).notNull(),previewMarkdown:text('preview_markdown'),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull(),finalizedAt:timestamp('finalized_at',{withTimezone:true})},t=>[index('briefs_chat_status_idx').on(t.chatId,t.status),uniqueIndex('brief_short_code_chat_unique').on(t.chatId,t.shortCode),check('brief_progress_range',sql`${t.progress} between 0 and 100`)]);
export const briefSessions=pgTable('brief_sessions',{id:uuid('id').defaultRandom().primaryKey(),briefId:uuid('brief_id').notNull().references(()=>briefs.id,{onDelete:'cascade'}),startedAt:timestamp('started_at',{withTimezone:true}).defaultNow().notNull(),endedAt:timestamp('ended_at',{withTimezone:true}),lastActivityAt:timestamp('last_activity_at',{withTimezone:true}).defaultNow().notNull(),modelSessionId:text('model_session_id')},t=>[index('brief_session_active_idx').on(t.briefId,t.endedAt)]);
export const messages=pgTable('messages',{id:uuid('id').defaultRandom().primaryKey(),updateId:bigint('update_id',{mode:'bigint'}).notNull(),telegramMessageId:text('telegram_message_id').notNull(),chatId:uuid('chat_id').notNull().references(()=>chats.id,{onDelete:'cascade'}),userId:uuid('user_id').notNull().references(()=>telegramUsers.id,{onDelete:'cascade'}),briefId:uuid('brief_id').notNull().references(()=>briefs.id,{onDelete:'cascade'}),sessionId:uuid('session_id').notNull().references(()=>briefSessions.id,{onDelete:'cascade'}),role:messageRole('role').default('user').notNull(),source:messageSource('source').notNull(),rawText:text('raw_text'),telegramFileId:text('telegram_file_id'),storedFilePath:text('stored_file_path'),transcript:text('transcript'),language:text('language'),stage:pipelineStage('stage').default('received').notNull(),failedStage:pipelineStage('failed_stage'),errorCode:text('error_code'),attempts:integer('attempts').default(0).notNull(),extracted:jsonb('extracted').$type<InterviewResult>(),applyResult:jsonb('apply_result'),modelCalls:jsonb('model_calls').$type<ModelCallMetadata[]>().default([]).notNull(),receivedAt:timestamp('received_at',{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull(),completedAt:timestamp('completed_at',{withTimezone:true})},t=>[uniqueIndex('messages_update_unique').on(t.updateId),uniqueIndex('messages_chat_telegram_message_unique').on(t.chatId,t.telegramMessageId),index('messages_brief_received_idx').on(t.briefId,t.receivedAt),index('messages_recovery_idx').on(t.stage,t.updatedAt)]);
export const briefFieldValues=pgTable('brief_field_values',{id:uuid('id').defaultRandom().primaryKey(),briefId:uuid('brief_id').notNull().references(()=>briefs.id,{onDelete:'cascade'}),fieldId:text('field_id').notNull(),value:jsonb('value').notNull(),status:fieldStatus('status').notNull(),confidence:numeric('confidence',{precision:4,scale:3}).notNull(),sourceMessageIds:jsonb('source_message_ids').$type<string[]>().notNull(),sourceQuote:text('source_quote'),reason:text('reason'),updatedAt:timestamp('updated_at',{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex('brief_field_id_unique').on(t.briefId,t.fieldId),check('confidence_range',sql`${t.confidence} between 0 and 1`)]);
export const briefFieldHistory=pgTable('brief_field_history',{id:uuid('id').defaultRandom().primaryKey(),briefId:uuid('brief_id').notNull().references(()=>briefs.id,{onDelete:'cascade'}),fieldId:text('field_id').notNull(),messageId:uuid('message_id').notNull().references(()=>messages.id,{onDelete:'cascade'}),previous:jsonb('previous'),next:jsonb('next').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('field_history_brief_idx').on(t.briefId,t.fieldId,t.createdAt)]);
export const briefSnapshots=pgTable('brief_snapshots',{id:uuid('id').defaultRandom().primaryKey(),briefId:uuid('brief_id').notNull().references(()=>briefs.id,{onDelete:'cascade'}).unique(),chatId:uuid('chat_id').notNull().references(()=>chats.id,{onDelete:'cascade'}),templateSnapshot:jsonb('template_snapshot').$type<TemplateDefinition>().notNull(),fields:jsonb('fields').$type<BriefFields>().notNull(),markdown:text('markdown').notNull(),messageIds:jsonb('message_ids').$type<string[]>().notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()});
